### ISSUE TITLE
Caching conflict with JCH Optimize plugin

### ISSUE THREAD

**Issue by eggzamummy** [litespeedtech/lscache-joomla#24]
Hello, we are using the JCH Optimize plugin along with LSCache.  There seems to be a strange timing issue with cache expirations.  Almost on a daily basis the site does not load properly (no CSS or JS).  The optimize plugin minifies and merges all css and js into a single file respectively and caches it.  It seems as though when the plugin dumps its cache and regenerates, the lscache cached page is looking for the combined js and css files which have now been deleted and re-cached/created by the plugin.  

Speaking with the developer of the JCH Optimize plugin they refresh the cache of the plugin daily:

This is a note from the JCH Optimize developer:

> When the cron runs it attempts to delete page cache using the Joomla! API with this call:
> 
> $cache = JCache::getInstance();
> $cache->clean('page');
> 
> If LiteCache is hooked into the Joomla! API, as it should, then it will get flushed. Are you sure you're not also caching the page in the browser? If so it would be best to disable browser caching.
> 
> You can verify with the developer if this call flushes the cache. It's better to do this using code than accessing a url as that will slow up the plugin. 

I'm not sure what is the best way to proceed.  It seems that there needs to be some sort of integration/communication so when the Optimize plugin dumps and re-caches that lscache is notified to purge it's cache as well...

**Comment by WuhuaChen** [comment]
@omikron  I already submit an update  to hook the JCH cache clean event on 6/17 ,  you can download the latest code from github, and run /package/buildPackage.sh to build the latest package then install it in Joomla.   I didn't find a way to hook Joomla $cache->clean('page') API , you can try this update first and give me feedback, I'll follow up this issue until it is solved.

**Comment by eggzamummy** [comment]
Thanks!  I updated the component/plugin this morning and will monitor and report.

**Comment by eggzamummy** [comment]
It looks like my login forms when used as a module now show "All Litespeed cache purged" instead of the login form.  I tried rendering as ESI but didn't help...

**Comment by WuhuaChen** [comment]
Sorry, It's a bug in last code release,  I just submit a bug fix .  you can download the latest code from github, and run /package/buildPackage.sh to build the latest package then install it in Joomla to fix it. thanks.

**Comment by eggzamummy** [comment]
It appears that we are still seeing some issues with the cache expiring in the JCH Optimize plugin and the litespeed cache not refreshing.  It seems that when the JCH Optimize plugin dumps its cache and regenerates the new css and js files that the litespeed cache is trying to still serve the old files resulting in 404s.  Also, it seems that now the utility URL to purge the cache is no longer working.  Is there a bit of code that I can add to the JCH Optimize plugin's cache purge routine?

**Comment by jimhill10** [comment]
I am having the same issue. As a work around I had to implement the CSS / JS combine function that was built into my template and no do it in JCH Optimize until I can sort this issue out.  I was seeing 404 errors in Akeeba Admin Tools.

**Comment by WuhuaChen** [comment]
I just released an update,  added an event "onLSCacheExpired", you can call it like:
        $dispatcher = JEventDispatcher::getInstance();
        $dispatcher->trigger("onLSCacheExpired");
You can add it to JCH Optimize plugin's cache purge routine after upgraded to latest LSCache plugin code.

**Comment by eggzamummy** [comment]
The JCH Optimize Team included the code above in their latest release.  It seems to be working better but still seeing timing issues.  Right now I have the cache TTL set to 10,000 minutes (1 week) and it seems to still be happening once a week.  What is a good setting for the TTL?

It also looks as though the Web interface to purge all LiteSpeed Cache is no longer working - just gives a white screen...

**Comment by eggzamummy** [comment]
Also, when calling the event "onLSCacheExpired" does this reset the cache timer for the site?  I'm trying to sync up the timing on the JCH Optimize setting the JCH plugin to 1440 TTL and LSCache to 1445 so that they will both reset at approximately the same time so they do not conflict.

**Comment by WuhuaChen** [comment]
about cache TTL,  if your cache TTL was set to 500 minutes, but your web page was visited every 1000 minutes,  then the page cache will be expired for next visitor.  if change cache TTL to 1200,  this page cache will never be expired as long as it was visited every 1000 minutes.  So normally set cache TTL greater than average interval of page visit will be better.   Of course some web page was visit frequently but others was rarely visited,  If no side effect found you can set a longer TTL to improve visitor experience.

The Web interface,  I found a minor bug, the link I put in GUI have a word "cleancache=xxxx" should be "cleanCache=xxxx" , I will fix it later.

when calling the event "onLSCacheExpired" , it doesn't reset the cache timer for the site .  the cache timer as reset at the first time of page visit after "onLSCacheExpired" event.

**Comment by eggzamummy** [comment]
Shouldn't cache TTL be driven by the potential change to content on the site rather than based on how frequently it is visited?  If you make updates to the site and your site is visited at a high rate, then those changes would never show without manually purging the cache.
Conversely, if the TTL functions as a timer based on last purge, then the site administrator would control the expiration rather than the frequency of the visitors....

**Comment by eggzamummy** [comment]
It appears that we are still having some issues with the integration between JCH Optimize and the LSCache.  It seems some pages that are not being visited frequently are potentially the issue.  It appears that when these pages are visited, the LSCache is serving old HTML where the JCH Optimize has already generated a new hash for their consolidated JS and CSS files so the cached HTML is pointing to an old (non existent) JS and CSS file.  The only way to resolve is to manually purge the LSCache.

**Comment by WuhuaChen** [comment]
Thanks for report. can you give me a test environment of your website with JCH configured as same as your product site. I need an back end admin panel account and a SFTP account which have read permission on joomla directory.  you can send it to wchen@litespeedtech.com and I will try my best to locate the problem and solve it.

**Comment by omikron** [comment]
Wordpress JCH+litespeed has the same issue... I wonder if it is related.

**Comment by jimhill10** [comment]
Thanks @uglyeoin

**Comment by uglyeoin** [comment]
@omikron go to your website, right click, press inspect element (instructions for Google Chrome), click on console, refresh the page.  If you see a red error message which says 403 forbidden you will know something is blocking the file.  Or feel free to share your URL to see if we can spot the issue.  Also let us know which security software you are using on WP.

**Comment by uglyeoin** [comment]
Just FYI I found that the rule I created caused one site to get hacked so I have changed my Gist.
